### ISSUE TITLE
html/body scrollTop issue

### ISSUE THREAD

**Issue by zcorpan** [operasoftware/devopera#242]
See https://groups.google.com/a/chromium.org/d/msg/blink-dev/75hVThfrJ08/YD9kSgQljFEJ

We need to reach out to web developers to not browser-sniff to choose between html.scrollTop and body.scrollTop but use something that works the same with either behavior so browsers can change to the saner behavior and in the future web developers can use only html.scrollTop.

* CSSOM View spec requires `html` in standards mode, `body` in quirks mode. IE/Gecko do this.
* Blink/WebKit currently always use `body`. Blink and WebKit tried to change but had to revert due to web compat where sites browser-sniff.
* IE12/Spartan will be sniffed as “WebKit” so will probably run into the same trouble as Blink did. It would be really sad if they had to copy the WebKit bug for compat, so Blink is interested in fixing it but we need webdev outreach.
* `scrollX`/`scrollY` on `window` exist as an alternative but they don’t exist in at least IE8 per http://stackoverflow.com/q/16618785/96656
* We need to consider both getter and setter — getting the scroll offset is easy but setting is less obvious.

I was pointed to https://gist.github.com/dperini/ac3d921d6a08f10fd10e by @dperini for a solution to get the right element without browser-sniffing. I haven’t checked in depth if it is what we want to recommend or if something else is better, most likely this has been solved in different ways.

(In theory both the viewport and the `body` element can be independently scrollable, and although the spec and browser impl cares about this, it’s probably not something anyone does outside of test cases, so we don’t need to burden web developers about this special case.)

**Comment by zcorpan** [comment]
The given script can return body in Gecko when both are scrollable, FWIW.
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3411

**Comment by zcorpan** [comment]
OK here's a script that I think should work cross-browser in both quirks and standards modes and continue to work when browsers change behavior towards the specced behavior, and returns the right element even if html and body are both scrollable. I haven't tested IE though but I think it should work.

```js
function getScrollingElement() {
  return document.compatMode !== 'CSS1Compat' ||
         'innerHeight' in window && document.body.scrollHeight === innerHeight ?
         document.body : document.documentElement;
}
```

**Comment by dperini** [comment]
zcorpan,
overwriting width, height and scroll style properties of both HTML and BODY elements with fixed values changes what the script is aiming to detect. So what would you expect ?
The script should work well on browser calculated contents height/width and the appropriate scrollbars should only be shown if needed (content area > visible area). Manipulation of these values through style or scripts are not detected by this simple check.
The scope of this snippet was detecting the non compliant Webkit scroll implementation in Standard Mode, in pages where the content area is bigger than the visible area and therefore scrollable (most times).

**Comment by zcorpan** [comment]
Throw away my script, it doesn't work in the common case! Oops. Blame jetlag. :)

I've looked into it a bit more and it seems to me @dperini's approach is the best. It might give the wrong result if body is itself scrollable, but as long as there are browsers worth caring about with this bug, you can't use scrollable body anyway, so it's moot point trying to support it.

**Comment by miketaylr** [comment]
I wrote about this here: https://miketaylr.com/posts/2014/11/document-body-scrollTop.html which has some links to fun™ bugs.

**Comment by zcorpan** [comment]
@miketaylr thx. The code snippet at the bottom makes no sense :)

**Comment by miketaylr** [comment]
:hankey: :gun:

**Comment by zcorpan** [comment]
https://lists.w3.org/Archives/Public/www-style/2015Apr/0108.html
->
http://dev.w3.org/csswg/cssom-view/#dom-document-scrollingelement

**Comment by zcorpan** [comment]
Polyfill: https://github.com/mathiasbynens/document.scrollingElement

**Comment by zcorpan** [comment]
If support for older browsers is necessary (IE < 8, Firefox < 4, Safari < 5, Opera < 12 -- [ref](http://kangax.github.io/compat-table/es5/#Object.defineProperty)) we can point to
http://johndyer.name/native-browser-get-set-properties-in-javascript/

**Comment by pepelsbey** [comment]
@zcorpan, there you go: [articles/_posts/2015-05-31-fixing-the-scrolltop-bug.md](https://github.com/operasoftware/devopera/blob/master/articles/_posts/2015-05-31-fixing-the-scrolltop-bug.md)

**Comment by mathiasbynens** [comment]
It’s happening! https://groups.google.com/a/chromium.org/d/msg/blink-dev/mJ5SlCj3CHc/jZ0YlpFyo4cJ

**Comment by brucelawson** [comment]
so what should we do?

**Comment by zcorpan** [comment]
Time to close?

**Comment by pepelsbey** [comment]
Yep.

**Comment by mathiasbynens** [comment]
https://dev.opera.com/articles/fixing-the-scrolltop-bug/
