### ISSUE TITLE
wifi, ble and javascript

### ISSUE THREAD

**Issue by sayanee** [operasoftware/devopera#243]
This is a new article idea that I have been discussing with @shwetank. After scanning through [the instructions](https://github.com/operasoftware/devopera/blob/master/CONTRIBUTING.md#article-submissions), we decided to create a new issue here.

I am planning to complete this article by **end February** with the following outline:

Title: **Wifi, BLE and JavaScript**

1. Introduction
    - current landscape of interacting with sensors using wifi, ble and other protocols
    - pre-requisites required
    - brief outline of the project
    - list of hardware components required
- Wifi with [Spark](https://www.spark.io/)
    - [JavaScript SDK](http://docs.spark.io/javascript/)
    - [Voodootiki Spark](https://github.com/voodootikigod/voodoospark)
- BLE with [TI Sensor Tag](http://www.ti.com/ww/en/wireless_connectivity/sensortag/index.shtml?INTC=SensorTag&HQS=sensortag-bt)
    - various npm like [noble](https://www.npmjs.com/package/noble)
- Conclusion
    - links to on-going specifications to lookout for e.g. [web bluetooth](https://github.com/WebBluetoothCG)
   - links to community initiatives such as [NodeBoats](https://www.facebook.com/media/set/?set=a.615900415180712.1073741830.224477610989663&type=3) or NodeBots

Throughout the article it will include pics (or gif) and videos and sectioned paragraph for better reading. Also, I will create the article instruction as a tiny project / demo for easier understanding. You can checkout some of [my previous article samples here](http://tutsplus.com/authors/sayanee-basu).

Let me know what you think :smiley:

**Comment by shwetank** [comment]
Hey Sanayee,

The topic looks great.  Let's do this. Looking forward to reading the draft. :thumbsup:
