### ISSUE TITLE
Bruce is blue (color profile info stripped/optimised out of image?)

### ISSUE THREAD

**Issue by patrickhlauke** [operasoftware/devopera#259]
On https://dev.opera.com/blog/colourful-opera-12-50-snapshot/, both pictures of Bruce are blue. I'm assuming both jpg images have been run through some kind of automated optimiser that perhaps stripped out the icc profile info?

**Comment by patrickhlauke** [comment]
for reference, the original can still be grabbed here https://web.archive.org/web/20120901223715/http://my.opera.com/ODIN/blog/2012/08/28/colourful-opera-12-50-snapshot @brucelawson

**Comment by pepelsbey** [comment]
Oops, will fix that. Thank you!

**Comment by mathiasbynens** [comment]
97a91a641967fdb38f02530916a4c6ad900da459

**Comment by pepelsbey** [comment]
Deployed, @brucelawson is pink again!

**Comment by patrickhlauke** [comment]
:+1:
