### ISSUE TITLE
The `Strict-Transport-Security` header is sent two times

### ISSUE THREAD

**Issue by alrra** [operasoftware/devopera#313]
```bash
$ curl -sSLI https://dev.opera.com/

HTTP/1.1 200 OK
Date: Thu, 02 Jul 2015 17:20:30 GMT
Server: Apache
---------> Strict-Transport-Security: max-age=15768000
Last-Modified: Wed, 01 Jul 2015 16:51:00 GMT
Accept-Ranges: bytes
Content-Length: 21895
Vary: Accept-Encoding
Cache-Control: max-age=0
Expires: Thu, 02 Jul 2015 17:20:30 GMT
X-UA-Compatible: IE=edge
X-Content-Type-Options: nosniff
---------> Strict-Transport-Security: max-age=31536000
Content-Type: text/html; charset=utf-8
```
  
  <img src="https://cloud.githubusercontent.com/assets/1223565/8483264/4779af80-20f8-11e5-8bb5-3b40e59a2439.png" width="300"  heigh="130">

In Firefox, since the values of the header seem to be combined, the console even warns about having an invalid `Strict-Transport-Security` header:

<img src="https://cloud.githubusercontent.com/assets/1223565/8483126/2f140608-20f7-11e5-8d62-0a27658edce9.png">

<img src="https://cloud.githubusercontent.com/assets/1223565/8483190/b46bd632-20f7-11e5-9479-49000e680a94.png" width="300"  heigh="130">

**Comment by mathiasbynens** [comment]
Twice the security™!

Thanks for spotting this. Fixed.
