### ISSUE TITLE
Understanding CSS transform matrix: x & y axes switched label:enhancement 

### ISSUE THREAD

**Issue by pascalculator** [operasoftware/devopera#355]
If I'm not mistaken, the article ["Understanding CSS transform matrix"](https://github.com/operasoftware/devopera/blob/master/articles/_posts/2012-05-23-understanding-the-css-transforms-matrix.md) has switched the x and y axes in [Figure2](https://dev.opera.com/articles/understanding-the-css-transforms-matrix/2.gif) and [Figure3](https://dev.opera.com/articles/understanding-the-css-transforms-matrix/4.gif). x-axis should be horizontal, y-axis should be vertical.

The images are hosted at https://github.com/operasoftware/devopera/tree/master/articles/understanding-the-css-transforms-matrix. Maybe @webinista has the original uncompressed images laying around, else I don't mind cutting and pasting the gifs and doing a pull request.

**Comment by pepelsbey** [comment]
Fixed, will be deployed shortly. Thank you!
