### ISSUE TITLE
Clean extension-docs URLs

### ISSUE THREAD

**Issue by pepelsbey** [operasoftware/devopera#365]
We at least 25 broken URLs all over Dev.Opera caused by two major rebuilds of extension docs. It needs to be cleaned up before updated docs could go live, IMO.

The simplest way is to open the project in ST and search by `extension-docs` string for `*.md` mask. In most cases it requires some editing not just auto-replacement that’s why I’ve assigned it to you @shwetank.

**Comment by shwetank** [comment]
Done
