### ISSUE TITLE
Build: service worker hash not generated correctly

### ISSUE THREAD

**Issue by mathiasbynens** [operasoftware/devopera#374]
https://dev.opera.com/service-worker.js still contains:

```js
const HASH = ''; // Calculated when running `gulp`.
```

**Comment by mathiasbynens** [comment]
@pepelsbey Can you check if I didn’t miss anything in this commit? Thanks.

**Comment by pepelsbey** [comment]
And what was the reason to include cache into `build` task? Final build command should be just `build` not `build:full`. Sub-commands are kind of “private API” there are only 3 public: `default`, `build`, `deploy`.

**Comment by mathiasbynens** [comment]
IIUC, `build` starts up the web server which we don’t want to have Travis doing.

**Comment by pepelsbey** [comment]
I’d rather remove `server` from the chain since it’s auto-building now
