### ISSUE TITLE
Let Apache know the server is on HTTPS, not HTTP

### ISSUE THREAD

**Issue by andreasbovens** [operasoftware/devopera#387]
Add redirect from https://dev.opera.com/extension-docs/ to https://dev.opera.com/extensions/

**Comment by mathiasbynens** [comment]
It’s already there: https://github.com/operasoftware/devopera/blob/c8b01e054876904b4317c47929dc170d9b4c2825/src/.htaccess#L24

```bash
$ curl -I 'https://dev.opera.com/extension-docs/'
HTTP/1.1 301 Moved Permanently
Cache-Control: max-age=0
Content-Type: text/html; charset=iso-8859-1
Date: Mon, 28 Dec 2015 18:34:41 GMT
Expires: Mon, 28 Dec 2015 18:34:41 GMT
Location: http://dev.opera.com/extensions/
Server: Apache
Connection: keep-alive
```

**Comment by mathiasbynens** [comment]
Not cool that it’s redirecting to `http://` though. Let’s fix that.

**Comment by mathiasbynens** [comment]
I’d rather not hardcore `https://dev.opera.com` in every single `RewriteRule`, so I’ve asked if this is possible: http://serverfault.com/q/746875/13896

**Comment by mathiasbynens** [comment]
Solved for now by hardcoding.

**Comment by mathiasbynens** [comment]
The proper way to solve this is by [specifying the `https://` scheme as part of the `ServerName`](http://serverfault.com/a/751097/13896).
