### ISSUE TITLE
Service worker: offline error page is also shown for redirects

### ISSUE THREAD

**Issue by mathiasbynens** [operasoftware/devopera#400]
1. `https://dev.opera.com/tv` 301 redirects to `https://dev.opera.com/tv/` (note the trailing slash).

2. We use the Fetch API in our server worker, here: https://github.com/operasoftware/devopera/blob/9a5ccd58c77e5daabb08e64a5143cd64a28071bc/src/service-worker.js#L56

3. The Fetch API returns a network error and thus throws an exception on redirects.

    To verify this, open <https://dev.opera.com/> and run this in the DevTools console:
    
    ```js
    fetch('/tv').catch(function(exception) {
      // The `catch` is only triggered if `fetch()` throws an exception,
      // which most likely happens due to the server being unreachable.
      // FIXME: it’s also triggered for redirects! :(
      console.error(
        'Fetch failed; returning offline page instead.',
        exception
      );
    });
    ```

4. However, ***in case of a redirect, we want to follow the redirect rather than show the offline page***. Is this possible?

----

If the answer to 4 is “no”, maybe we need to go deeper. This is how we currently check if the service worker (and thus the above code) needs to kick in:

```js
if (event.request.method == 'GET' &&
  event.request.headers.get('accept').includes('text/html')) {
  // It’s a GET request for an HTML document.
}
```

A better test would be [`if (event.request.mode == 'navigate') { … }`](https://fetch.spec.whatwg.org/#concept-request-mode) but that’s [not supported yet in Chromium](https://code.google.com/p/chromium/issues/detail?id=580526).

Is there another way to avoid this issue?

**Comment by jakearchibald** [comment]
> https://dev.opera.com/tv 301 redirects to https://dev.opera.com/tv/ (note the trailing slash).

It redirects to **http**://dev.opera.com/tv/, and that's the problem, you're crossing the schemes :laughing:.

You can confirm this with:

```sh
curl -s -D - https://dev.opera.com/tv -o /dev/null
```

However, `fetch(event.request)` should have worked fine since it has the manual redirect flag set, which you can also set yourself with `fetch('/tv', {redirect: 'manual'})`.

This is broken in Chrome stable because of https://code.google.com/p/chromium/issues/detail?id=546495, but it's fixed in Canary.

**Comment by mathiasbynens** [comment]
Ah, `curl -sI https://dev.opera.com/` indeed :blush: `beersMathiasOwesJake++`

Since `tv` is a directory, this is essentially due to [Apache thinking dev.opera.com is on HTTP](https://github.com/operasoftware/devopera/issues/387#issuecomment-169035646). Closing.

**Comment by jakearchibald** [comment]
My blog appears to do the same. I should fix that.

**Comment by mathiasbynens** [comment]
FWIW, on Apache this is a matter of [specifying the `https://` scheme as part of the `ServerName`](http://serverfault.com/a/751097/13896).
