### ISSUE TITLE
Atom feed not parsing

### ISSUE THREAD

**Issue by ohmanger** [operasoftware/devopera#409]
https://dev.opera.com/feed/

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdev.opera.com%2Ffeed%2F

Doesn't seem to be parsing in RSSOwl. Seems to be due to the white space before the `<xml>` element.

**Comment by mathiasbynens** [comment]
@pepelsbey Didn’t we use to XML-minify the feeds?

**Comment by pepelsbey** [comment]
@mathiasbynens, XML minification is back again by 57b2710

**Comment by mathiasbynens** [comment]
:+1:
