### ISSUE TITLE
Addon: setIcon error and buttons in chrome notification api

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [operasoftware/devopera#425]
On Opera Beta (36.0.2130.29) on Linux I got this error when my addon try running `Unchecked runtime.lastError while running browserAction.setIcon: Icon invalid.` The path and icon type are supposed to be right, as it work on Opera Stable version. `chrome.browserAction.setIcon({path: "/data/live_online.svg"});` Maybe it's a problem linked to svg?

Opera 35.0 use the same Chromium base version 48.0.2564.116, so it would be very interesting to support buttons too, in notifications https://developer.chrome.com/extensions/notifications#property-NotificationOptions-buttons

**Comment by shwetank** [comment]
>Maybe it's a problem linked to svg?

Yes, SVG won't work. 

Btw, a much better place to ask questions regarding addons would be on the addons forums here https://forums.opera.com/categories/en-opera-add-ons
