### ISSUE TITLE
duoble behavior of central button in speed dial

### ISSUE THREAD

**Issue by bebabi34** [operasoftware/devopera#463]
apologize for my English

on Linux, central mouse click on some speed any box:
1. open the link in new tab (correct)
AND
2. add new box for address in clipboard (misbehavior)

central clicking out of any box, only 2. happens (correct)

**Comment by pepelsbey** [comment]
There’s [bug wizard](https://bugs.opera.com/wizard/) for that. This is [Dev.Opera](https://dev.opera.com) site repository.
