### ISSUE TITLE
Opera Startscreen more Searchengines

### ISSUE THREAD

**Issue by Sythys** [operasoftware/devopera#467]
In the Opera starting screen is a search bar that only supports google search.

I'd like to see an option to use it in the customisation bar on the right.

Ps.: mine is in german sorry for that.
http://image.prntscr.com/image/62e9d227d0304acab5770f7b6540a87c.png

**Comment by pepelsbey** [comment]
Please address your issues in [Desktop Team in blog](http://www.opera.com/blogs/desktop/) or on [Opera Forums](http://forums.opera.com/).
