### ISSUE TITLE
Opera extensions don't support "requireInteraction" in Notification?

### ISSUE THREAD

**Issue by brcontainer** [operasoftware/devopera#494]
The https://dev.opera.com/extensions/apis/ don't mention anything about it.

- This is a bug or limitation?
- Are there plans to release this feature?

Thanks! Sorry if posted in an inappropriate place, I asked the forum and elsewhere and nobody gives me feedback.

**Comment by shwetank** [comment]
Hi,

The forums are indeed the correct place to ask. Sorry for you not getting that answer yet. I'll comment on the forums itself after checking with some of the engineering team on this. `requireInteraction` is fairly new. We'll be updating the docs soon on it as well.

**Comment by brcontainer** [comment]
@shwetank I am grateful for future updates in the docs. Thanks!
