### ISSUE TITLE
Article idea: Living Styleguide (Using Nodejs, node-kss, KSS Commenting style)

### ISSUE THREAD

**Issue by fokusferit** [operasoftware/devopera#495]
The article would be about a short overview, why a living styleguide is important, what KSS is basically and in specific the node-kss project. 

There are a lot of different approaches for creating a living style guide and I still like the simplicity and easy use of KSS combined with this node-kss project.

Additionally, I would show how to integrate a automated generation of the styleguide with gulp/grunt, means if a developer is just commenting appropriately generating the styleguide is automatically achieved.

**Comment by zcorpan** [comment]
Sorry for the delay! I hope you had a chance to write about your idea and get it published somewhere; I'm not sure it's a good fit for dev.opera at this time.
