### ISSUE TITLE
Extended hex color notations (#rgba, #rrggbbaa) aren't in stable channel

### ISSUE THREAD

**Issue by myakura** [operasoftware/devopera#499]
re https://dev.opera.com/blog/opera-39/#css-alpha-channel-for-rgb-colors-in-hex-notation

I just found that [Chrome team disabled them right before shipping M52 :(](https://bugs.chromium.org/p/chromium/issues/detail?id=618518), so they aren't available in Chrome 52 and Opera 39 unless turning the experimental features flag on.

**Comment by mathiasbynens** [comment]
Good catch — thanks!
