### ISSUE TITLE
progressive web app install banner doesn't show on opera mobile but does not chrome mobile

### ISSUE THREAD

**Issue by jasan-s** [operasoftware/devopera#502]
i have enabled “Bypass user engagement checks”  fro both browsers (chrome & opera) on my android mobile device. both are up to date as of today opera version 37.0.2192.105088. Yet add to homescreen banner only pops up in chrome not in opera for my webapp. I tested the wavepad app and the banner shows up just fine. Are there different requirements that i have not fulfilled from opera?

**Comment by pepelsbey** [comment]
This repository is dedicated specifically to [Dev.Opera](https://dev.opera.com/) development. Please consider using [Opera forums](https://forums.opera.com/) or ask [@ODevRel](https://twitter.com/ODevRel) or [@andreasbovens](https://twitter.com/andreasbovens) on Twitter.
