### ISSUE TITLE
The Upload Extensions Form doesn't work

### ISSUE THREAD

**Issue by ovidiaconescu** [operasoftware/devopera#505]
https://addons.opera.com/developer/upload/- does not load properly

https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/CACHE/css/66a088d8e77d.css Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/header-footer/css/img/opera-icon-header.c6f9a9d4173c.png Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/CACHE/js/219aaa7fe74d.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/vendor/ui-bootstrap/1.1.2/ui-bootstrap-tpls.eba2f5db2466.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/file-upload/fileUpload.c8dd076a1043.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/editable-field/editableField.700f1a707b78.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/history-tabs/historyTabs.9ef6747f9fbb.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/panel/panel.6f7508f63f76.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/package-list/packageList.2ea782116bb4.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/package/package.583e41009c7d.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/components/package-version/packageVersion.ec33132a9eee.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/services.b8594ebdaca2.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/routing.d859218cde7a.js Failed to load resource: net::ERR_CONNECTION_RESET
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/developer/app/app.bf92316fbb92.js Failed to load resource: net::ERR_CONNECTION_RESET
addons.opera.com/:148 Uncaught ReferenceError: angular is not defined
https://cdn0.opera-mini.net/cdn_v1/files/download/addonsfs/pub/static/header-footer/favicon/ico/opera.ced696a02c2c.ico Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by pepelsbey** [comment]
This repository is not a proper place for report bugs for extensions catalog. It’s dedicated specifically to [Dev.Opera](https://dev.opera.com/). And there’s a hint at the top of this form:

> If you encounter any problems with the add-ons management panel, please describe them on English version of [Opera add-ons forum](https://forums.opera.com/categories/en-opera-add-ons).

Please use Opera add-ons forum for that, thank you.
