### ISSUE TITLE
Persistent GUI bug in latest dev edition

### ISSUE THREAD

**Issue by JIVS** [operasoftware/devopera#507]
The entire GUI is nothing but one monochromatic grey bar now, even the buttons in the quick start screen wont respond but any tabs left from the previous session with load, although its impossible to interact with the site.

Issues started while playing a youtube video and persisted even after closing the app directly from the task manager on win10

Is this a known problem? couldn't find anything similar out there.

**Comment by pepelsbey** [comment]
This is not a suitable repository for such bug reports, please use [Opera bug wizard](https://bugs.opera.com/wizard/desktop)
