### ISSUE TITLE
chrome.runtime.sendMessage is an empty function

### ISSUE THREAD

**Issue by atheeq** [operasoftware/devopera#512]
In the success callback of opr.addons.installExtenion, chrome.runtime.sendMessage is an empty function. So, basically I need to reload the page after inline installation in order to communicate with the extension. I am using Opera 39.0.2256.71 on Mac OS X 10.10.5 64-bit

chrome.runtime.sendMessage works when I already have the extension installed from a webpage.

**Comment by pepelsbey** [comment]
This repository is related to Dev.Opera site development and site’s content only. It’s not the right place for filing bugs. Please contact @shwetank directly.

**Comment by shwetank** [comment]
Contacted directly. :) Following up.
