### ISSUE TITLE
Article Idea : The New Start Page - Working With the speed dial and search bar 

### ISSUE THREAD

**Issue by NishantSinghChandel** [operasoftware/devopera#516]
## What next for the opera UI/ UX?
From Opera 30 onwards, the start page will have a interactive new look. It introduces various design improvements start page customization and  to the sizes of the speed dial tiles also with the most used site tiles.

> Progress is impossible without change, and those who cannot change their minds cannot change anything. 

Till now the opera is updating very rapidly but as a user friendly UI there are so many things that are not perfect in the opera browser. These are the small negligence factor which can be modified so that it will be helpful for the user. The speed dial tiles was always having a great experience and a helpful concept for user. The new update is following the same style like the older one. I am going to share and idea regarding this and overall speed dial tiles look much better. 

There is small problem when we maximize or minimize the start page the speed tiles get increased and decreased.

### **The start page size get reduced**

![image](https://cloud.githubusercontent.com/assets/17858766/19113587/0be80c96-8b28-11e6-85d8-f905ef611403.png)

Here the search bar is also getting minimized and it is not a user friendly customization because when a user try to search something by writing on search bar it is not clearly visible because of small in size but we like to the speed dial tiles small, as speed dial tiles can be identified by its icon image which is large enough to recognize. 

### **The start page get maximized**

![image](https://cloud.githubusercontent.com/assets/17858766/19113614/2fbf3bee-8b28-11e6-88a6-12037610e626.png)

However, above image shows that the search bar is maximized by it also not look great. 

### **The start page looks good at this size** 

![image](https://cloud.githubusercontent.com/assets/17858766/19113638/44f4bcbe-8b28-11e6-8dcf-28b8325f7b28.png)

A solution to this is to introduce new way to customize speed dial as well as search bar.This solves the legibility issue by making the text very easy to read, some user might want to not have this type of features depending on their preference.

So the opera team must consider these problem to make it a good as well as user friendly start page. This gives greater control in the hands of the users.

As a user there must be two things which can be modified or updated in the opera that are as follows:

- Different zoom option for the search bar.

- Different zoom option for the speed dial tiles.

- The tiles shape for speed dial must be a sphere because Opera icon represented by a big circular 'O'. Therefore it is a good practice to change the speed dial tiles shape.

As a observer and a great user of Opera there are few more things that can be changed to make the Opera browser more popular and attractive, also user friendly.
The changes are as follows-

 1. The speed dial shape must be circular, the reason is already mentioned above.

 2. When we hover the speed dial tiles there must be an animation on hovering.

 3. There is a separate bar in the right side of start page for the folder **not** in the same grid with the individual tiles.

 4. Just like a battery bar on the top of browser there must be a browser locker which lock the browser so that no body without the pin access the browser.

 5. There must be option to change the color theme of the browser.

These are the small changes that is required for the Opera browser and as a student of computer science who is interested in UI/UX I would like to see these types of changes for the opera browser. 

Hoping that these changes may bring Opera popularity and more user.
For any query and further assistance contact me  [Nishant Singh](http://www.nishantsingh.tk).

**Comment by pepelsbey** [comment]
Dev.Opera is the place for web or extensions developers, not regular Opera users. I don’t think this would make a good article in this direction.

**Comment by ZenFi** [comment]
But good idea for them to be circular. +1
Also the user should/could have little more control over speed dial  / start page, like:

- size of SD items
- shape of SD items
- ability to change/reload/set "icons" similar like in "heart" menu
- ability to set default search engine freely (both SD + omnibox)

There's many things how SD could serve the user better, but this is for starters. Opera's friends will be glad for any improvements - as long as there will be improvements.

**Comment by lionux1988** [comment]
Please stop or make adjustments towards income at my desired bank.

Re: [operasoftware/devopera] Article Idea : The New Start Page - Working
With the speed dial and search bar (#516)

On Aug 21, 2017 8:36 AM, "ZENFI" <notifications@github.com> wrote:

But good idea for them to be circular. +1
Also the user should/could have little more control over speed dial / start
page, like:

   - size of SD items
   - shape of SD items
   - ability to change/reload/set "icons" similar like in "heart" menu
   - ability to set default search engine freely (both SD + omnibox)

There's many things how SD could serve the user better, but this is for
starters. Opera's friends will be glad for any improvements - as long as
there will be improvements.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/operasoftware/devopera/issues/516#issuecomment-323777663>,
or mute the thread

**Comment by EC-O-DE** [comment]
Pardon sir. But how to submit/reach this feedback for OPR devs?

**Comment by zcorpan** [comment]
@EC-O-DE I recommend commenting at https://blogs.opera.com/desktop/ instead.
