### ISSUE TITLE
Geolocation is not working

### ISSUE THREAD

**Issue by lmsantin** [operasoftware/devopera#521]
Try these urls in Opera browser:

[https://developers.google.com/maps/documentation/javascript/examples/map-geolocation](url)
[https://dev.opera.com/articles/w3c-geolocation-api/basic_geolocation_example.htm](url)

and these links are broken:

[https://dev.opera.com/dev.opera.com/index.html](url)
[https://dev.opera.com/dev.opera.com/articles/view/how-to-use-the-w3c-geolocation-api/index.html](url)

**Comment by pepelsbey** [comment]
URL are fixed now and will be deployed shortly, thank you!

But this is not a suitable repository for reporting problems with Gep API, please use [Opera bug wizard](https://bugs.opera.com/wizard/desktop) instead.
