### ISSUE TITLE
https://ok.ru/video/240820226628

### ISSUE THREAD

**Issue by tagataho** [operasoftware/devopera#526]
Hi
I downloaded and setup opera today.
but your new feature pop out video do not working on https://ok.ru/

you can test on https://ok.ru/video/240820226628

please fix it.

**Comment by zcorpan** [comment]
Works for me!
<img width="1453" alt="okru" src="https://cloud.githubusercontent.com/assets/244772/22875674/44c330b6-f1cd-11e6-9435-92f7f3ea3cb4.png">

Please report here with more details if you're still having trouble.
https://bugs.opera.com/wizard/

**Comment by tagataho** [comment]
How did you do this?

**Comment by zcorpan** [comment]
Clicked on the popout thingy at the top of the video

<img width="445" alt="untitled" src="https://cloud.githubusercontent.com/assets/244772/22924994/731f1eea-f2a7-11e6-8adc-c1fb6093df2f.png">

**Comment by tagataho** [comment]
i use in windows 7.

there is no popout button :(((

**Comment by zcorpan** [comment]
Please report at https://bugs.opera.com/wizard/
