### ISSUE TITLE
Not Save My Words in Opera

### ISSUE THREAD

**Issue by tagataho** [operasoftware/devopera#527]
Hi
I do not know how i can describe my problem. so i give you two screenshot, after you see that, you can understand what i mean.

Firefox Screenshot: http://prnt.sc/e7pcg0

Opera Screenshot: http://prntscr.com/e7pdge

I want to use like Firefox, how can i do that? Can you add this feature on Opera ?

**Comment by zcorpan** [comment]
Do you mean a drop-down with previous searches? That works for me when I press down arrow. But this repo is not the right place for bug reports or feature requests in Opera. 😊

https://bugs.opera.com/wizard/

**Comment by tagataho** [comment]
How do you work for you? I will crazy; i am shocked... :((((

**Comment by zcorpan** [comment]
With this URL https://bugs.opera.com/wizard/ after I search for a couple of things and then go back, empty the field, and press down arrow, I get the previous searches in a dropdown. This is on macOS. If it doesn't work for you again please report an issue there with more details.

![dropdown](https://cloud.githubusercontent.com/assets/244772/22924698/67adbe28-f2a6-11e6-989f-65bdf1f146bd.png)
