### ISSUE TITLE
Scroll button doesn't work

### ISSUE THREAD

**Issue by astoria-software** [operasoftware/devopera#537]
After click link via middle mouse button/scroll button Opera do nothing. It should open link in new tab like other browsers.

Version:	45.0.2552.812 (PGO)
Update chanell:	Stable
OS:	Windows 10 64-bit

**Comment by zcorpan** [comment]
Please report here: https://bugs.opera.com/wizard/desktop

Thanks!

**Comment by astoria-software** [comment]
Works on 45.0.2552.888, thanks Opera developers!
