### ISSUE TITLE
Reorder extensions icons on adress bar

### ISSUE THREAD

**Issue by astoria-software** [operasoftware/devopera#538]
It's feature request. I think is very comfortable to may reorder icons of extensions on adress bar. It works on Chrome and FF.

Version:	45.0.2552.812 (PGO)
Update chanell:	Stable
OS:	Windows 10 64-bit

**Comment by zcorpan** [comment]
Please report here: https://bugs.opera.com/wizard/desktop

Thanks!

**Comment by astoria-software** [comment]
Are you sure? It's not a bug, it's feature request...

**Comment by zcorpan** [comment]
Yep ^_^ This repo is for this web site: https://dev.opera.com/

**Comment by astoria-software** [comment]
Oh, sorry.
Reported on https://bugs.opera.com/wizard/desktop (DNAWIZ-16880).

**Comment by lionux1988** [comment]
You mean Bugreport?
