### ISSUE TITLE
Context menu is not visible on dark GTK theme

### ISSUE THREAD

**Issue by alkaef** [operasoftware/devopera#539]
**Description:**
_OS: Ubuntu 16.04 LTS
Desktop: Gnome 3.20_

The context menu & the right click menu is not visible whenever I use dark theme variant (e.g. Arc-Dark and Flat-Plat-dark). The text color in the context menu is white and so does the background. I think opera should also change the context background color when dark theme is selected and have the option to automatically change its theme (light/dark) based on current GTK theme. 

**Steps to reproduce:**
  1. Open opera in light GTK theme (Arc or Flat-Plat)
  2. RIght click or open menu to show context
  3. The right click menu is **visible**
  4. Open tweak tool
  5. Change theme to dark variant (Arc-Dark or Flat-Plat-dark)
  6. Right click or open menu to show context
  7. Text is **not visible** due to white background color in the context menu (even when using dark opera theme) 
 
**Actual result:**
Opera doesn't automatically change to dark variant theme (and the context menu background), thus text is not visible in the context menu

**Expected result:**
Opera should automatically change to dark variant theme (and change the context menu background to dark color) so the context menu is visible

**Pictures:**
Light GTK Theme
![light](https://cloud.githubusercontent.com/assets/13399275/26545481/f37149e4-448f-11e7-91ee-d386160cbd73.jpg)
Dark GTK Theme
![dark](https://cloud.githubusercontent.com/assets/13399275/26545480/f36cc54a-448f-11e7-8f72-4237c52d30e4.jpg)

**Summary:**
1. Issue : Context color is not visible in dark theme
2. Feature request : Automatically change theme based on current GTK theme

 _Thank you_

**Comment by lionux1988** [comment]
https://Dirve.Google.Com/my-drive/(-Subject-"Shared with Me")

Find files shared with you
Here's what you can see in "Shared with me:"

Files shared with you.
Folders shared with you.
Files shared with a link that anyone can view.
Starting with the most recent file that was shared with you, you’ll see:

The date the file was shared with you.
The owner of the file.
The document type.
COMPUTER ANDROIDIPHONE & IPAD
Add files to "My Drive"
If you want to organize shared files, add them to "My Drive."

Go to drive.google.com.
On the left, click Shared with me.
Click the files or folders you want to add to your drive.
In the top right, click Add to my Drive Add to My Drive.
Click Organize.
Choose the folder you want to add to.
Click Move here.
Related articles
Share files from Google Drive
Stop or change how a file is shared
Transfer file ownership
Share folders in Google Drive

[+1206313004@FCC-id-number.text/ZNFK550BN[Google_Inc]

**Comment by zcorpan** [comment]
Please report here: https://bugs.opera.com/wizard/desktop

Thanks!
