### ISSUE TITLE
/usr/lib64/opera-developer/setup_repo.sh: line 163: install_newer_key: command not found

### ISSUE THREAD

**Issue by a1exus** [operasoftware/devopera#544]
I'm getting following email:

> Subject: Output from your job      146
> 
> /usr/lib64/opera-developer/setup_repo.sh: line 163: install_newer_key: command not found
> 

My environment:

```
$ rpm -q opera-developer
opera-developer-48.0.2657.0-0.x86_64
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
$ 
```

**Comment by fsoder** [comment]
This is not the appropriate forum for this type of query. I've opened a ticket in our bug-tracker for this issue. For reference, the issue number is DNA-62760. Thank you!
