### ISSUE TITLE
JS engine works wrong.

### ISSUE THREAD

**Issue by asamushenkov** [operasoftware/devopera#546]
Hi. It looks like JS engine in the latest version of Opera browser works wrong. Here you can find code snippet to test it:
```
for(var index=0; index < 10000;++index) { 
    [1,2].reduce(function (a1,a2, index) { 
        if (index === 0) {
            console.log('error', a1, a2, index);
        }
    });
}
```
and it gives me the next result:

![image](https://user-images.githubusercontent.com/11872649/29003710-258c853c-7ac4-11e7-8580-a50a50ecf949.png)

How it should work: 
_If initialValue isn't provided, reduce will execute the callback function starting at index 1, skipping the first index. If initialValue is provided, it will start at index 0._

There are a lot of sites that do not work correctly cause of this issue. For instance https://www.tradingview.com/chart/?symbol=AAPL has some problems with the chart. 

Thank you.

**Comment by asamushenkov** [comment]
Sorry if it is a wrong repository. Can you move it to the right one. I have submitted this issue one month ago (DNAWIZ-17788) and still haven't received any feedback.

**Comment by fsoder** [comment]
You're right that this is not the right repository - unfortunately there's no "right" one here, and the bug you filed is the correct channel... so sorry that it hasn't received any attention =/

That being said, this sounds a bit like https://bugs.chromium.org/p/chromium/issues/detail?id=709782 - if it is, then it should've been fixed already and be available at least in 47 (and hopefully 46 as well. It didn't reproduce in the version of 46 I tested in.)

**Comment by asamushenkov** [comment]
I am using now Opera 46.0.2597.57 (PGO). Have checked it on several machines.

**Comment by fsoder** [comment]
Could you try checking in 47 (or anything greater than 46)?

**Comment by asamushenkov** [comment]
Just checked Opera beta 47.0.2631.34 (PGO). Looks like new version doesn't have this issue. Will wait for new release. xD

Thank you.
