### ISSUE TITLE
When will my add on get reviewed?

### ISSUE THREAD

**Issue by lajpatshah** [operasoftware/devopera#554]
Sorry to write this issue here as I couldn't find appropriate support link

I had submitted my addon on 19 Sep but it is yet to be reviewed by moderators.

Can someone guide me how long does it takes & how can I get my add on to moderators attention?

**Comment by szuliq** [comment]
Can you please share your username on Opera's store?

**Comment by lajpatshah** [comment]
sorry have deleted my account on opera since the delay is too much in case I need to make any corrections. was hoping that your store would be a good addition to my app....
