### ISSUE TITLE
Sorting bookmarks via context menu in bookmark bar is no longer available

### ISSUE THREAD

**Issue by acidstout** [operasoftware/devopera#565]
The context menu of the bookmark bar (e.g. if you right-click a folder in the bookmark bar) does no longer show "Sort alphabetically". The menu entry is still available in the context menu of the bookmarks in the respective bookmarks tab (e.g. if you click Ctrl+Shift+B). So why was it removed in the context menu of the bookmark bar itself?

**Comment by bratell-at-opera** [comment]
You will not reach anyone working with the desktop bookmark UI through this issue tracker. I forwarded your question to some people that might be interested but you will have better luck at https://forums.opera.com/ or if you think you noticed a bug https://bugs.opera.com/wizard/desktop .
