### ISSUE TITLE
Dev Opera stuck on "Verify Email"

### ISSUE THREAD

**Issue by dovy** [operasoftware/devopera#566]
Hey there! I previously submitted an opera extension and I wanted to push an update. For some reason it says I need to verify my email address. I've tried changing my email too and verifying that new address to no success.

Any ideas?

https://addons.opera.com/developer/

I would have submit a support ticket elsewhere, but you don't exactly have a contact form on your site.  ;)

**Comment by szuliq** [comment]
Hi. Your account is now synced. We've had some bug. We're working on it. Thanks for reporting!
