### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [operasoftware/devopera#569]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop.

I use **Arch Linux**, and while there is an "official" package for **Opera**, it would be awesome to have the option to install it via a Flatpak.

**Comment by avl7771** [comment]
Why choose Flatpak over Snap or AppImage?

**Comment by x80486** [comment]
I think the first thing that comes to my mind is the _adoption_ of the technology in general. Flatpaks and Snaps has some clear (out-of-the-box) differences compared to AppImages, so I think we can focus on those two.

Snaps has some disadvantages since Ubuntu has total control over it — basically the non-independence of the provider; having to agree with the Ubuntu CLA to contribute, a centralized store (it is possible to create independent repositories, but it is complex); they also _still_ depends on an LSM like AppArmor (Solus OS had to integrate it into the system to offer all the features of the format, something I doubt all distros would do).

With Flatpaks everything is open sourced and is not _as centralized_ as Snaps. Moreover, they are intended on delivering software to desktops — Snap packages are basically just server technology that Canonical has adopted for the desktop...but works for both.

My preference is for Flatpaks, but both: Snaps and Flatpaks deliver the promise (more or less) of a "universal package format".

**Comment by x80486** [comment]
So, you guys silently made a Snap package with no feedback whatsoever. Are there any chances you can make a Flatpak?

Most distros won't be able to use the Snap package.
