### ISSUE TITLE
Focus address bar not select all automatically

### ISSUE THREAD

**Issue by mashimaroa15** [operasoftware/devopera#570]
As I mentioned on the title, when I use CTRL+L or CTRL+E, the cursor does focus on the address bar but the browser does not select all text automatically. This bug makes the navigation much less practical.

**Comment by mashimaroa15** [comment]
Version: | 54.0.2920.0 - Opera is up to date
-- | --
developer
Windows 7 64-bit

**Comment by nowaktz** [comment]
Works for me, closing.
