### ISSUE TITLE
Animated wallpaper not working since 53.0.2880.0

### ISSUE THREAD

**Issue by ghost** [operasoftware/devopera#572]
ON upgraded opera-developer with version 64.0.2929.0., animated wallpaper load to crash page. If i try to access settings it also load to crash page.
Tried with new profile, i get the same result (crash page) if i try to add an animated wallpaper from addon page.
Animated wallpaper are not working since version 53.0.2880.0 on my system.

On versions : 53.0.2893, 2900, 2906, 54.0.2913. 2920 animated wallpapers are frozen. Those were comfirm not working with leocg, moderator on opera forum.

[opera forum](https://forums.opera.com/topic/25378/new-opera-developer-53/38)

Os : arch linux
Kernel : current with ck patch set
Video : nvidia with ck wrapper version 390.48

**Comment by nowaktz** [comment]
Works for me, closing. Please reopen if still an issue.
