### ISSUE TITLE
Deadlink

### ISSUE THREAD

**Issue by peterennis** [operasoftware/devopera#577]
From here:
https://www.w3.org/wiki/Dynamic_style_-_manipulating_CSS_with_JavaScript

This example:
https://dev.opera.com/articles/dynamic-style-css-javascript/changingelementstyles.html

![capture339](https://user-images.githubusercontent.com/140737/42301724-b8393e72-7fcb-11e8-916a-b9f7f4a269f8.png)

**Comment by fsoder** [comment]
See #598
