### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by dwbraughler** [operasoftware/devopera#598]
https://www.w3.org/wiki/Dynamic_style_-_manipulating_CSS_with_JavaScript links to 
https://dev.opera.com/articles/dynamic-style-css-javascript/changingelementstyles.html
which doesn't exist.

**Comment by bratell-at-opera** [comment]
Thanks for your report but I think this has to be fixed on the W3 side (in some way).

The article probably disappeared from dev.opera.com in 2013 when the site was reworked and I don't have any history beyond that. So the right thing is to change the W3 wiki to not include the dangling link. I don't obviously see how to do that but it should be possible.

**Comment by fsoder** [comment]
This article was moved/relocated to the "WebPlatform.org" documentation project. This project was later discontinued. It's still possible to access that article at https://webplatform.github.io/docs/tutorials/Dynamic_style_-_manipulating_CSS_with_JavaScript/ (or in the devopera-static-backup repo).
