### ISSUE TITLE
Web3 connect not happening for dapp

### ISSUE THREAD

**Issue by lrgeoemtry** [operasoftware/devopera#600]
Hi
Love the web3 in browser
I am the cto of hipr.one a puzzle game on ethereum 
![screenshot_20181205-090506_ h erc](https://user-images.githubusercontent.com/25958096/49974722-a5209f80-ff08-11e8-8360-d90a38f1cd05.jpg).

For some reason we have it working in trust and metamask but we cant get it moving on opera. Https://github.com/hercone/restful-hipr is the code base. 

We're also working on the up and an up and coming project CryptoFootball.
[cryptofootballteaserstadium_test0001](https://user-images.githubusercontent.com/25958096/49974700-81f5f000-ff08-11e8-9fb3-c7fa5e8a9824.jpg)

![screenshot004](https://user-images.githubusercontent.com/25958096/49974689-71457a00-ff08-11e8-8db7-63e26d19548a.png)

![cards retro test 8](https://user-images.githubusercontent.com/25958096/49974655-53781500-ff08-11e8-8308-b17a2b06d82f.png)

Any help is appreciated , would be really cool if we could be on the home page of the dapps browser..

May I suggest make it A LOT easier to find the wallet. 

The on boarding is awesome and I look forward to working with your team moving forward :) 

Cheers! 
LrG

**Comment by serso** [comment]
Hi @lrgeoemtry,
Please contact the crypto-wallet team directly via walletfeedback-external@opera.com.
The difference between us and Metamask is that we don't inject web3.js automatically which breaks some dapps. That is done intentionally as the dapp should be self-contained (as any other web-page) and shouldn't rely on JavaScript injection. See also [Metamask's FAQ](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#partly_sunny-web3---ethereum-browser-environment-check):
> You can use the injected Web3.js directly, but the best practice is to explicitly bundle the version of web3.js you used during development.

**Comment by lrgeoemtry** [comment]
Sent. Please close this issue @serso
