### ISSUE TITLE
Needs more features: split view, web panels, omnisidebar

### ISSUE THREAD

**Issue by EC-O-DE** [operasoftware/devopera#602]
Needs more features: split view, web panels, omnisidebar

**Comment by EC-O-DE** [comment]
notes!

**Comment by EC-O-DE** [comment]
https://github.com/ric2b/Vivaldi-browser/tree/master/notes

**Comment by EC-O-DE** [comment]
https://github.com/mozilla/side-view/

**Comment by bratell-at-opera** [comment]
Hi EC-O-DE. This is unfortunately not the place to reach the opera for desktop development team. devopera is a site aimed at web developers using Opera or developing for Opera/Chromium.

You can find our desktop development team via our forum at https://forums.opera.com/category/5/opera-for-computers
