### ISSUE TITLE
Opera, bring back Presto, please!

### ISSUE THREAD

**Issue by AnClark** [operasoftware/devopera#609]
There used to be five main-stream browser engines:

|Engine|Vendor|Usage Example|Source State|
|----------|-----------|------------|---------------|
|Chromium|Google|Chrome, Opera after 12.18|Opensource|
|Gecko|Mozilla|FireFox|Opensource|
|Presto|Opera|Opera before 12.18 (includes)|Proprietary|
|Apple WebKit|Apple|Safari|Proprietary|
|Trident (MSHTML)|Microsoft|Internet Explorer|Proprietary|

Of course, the most lightweight engine is Presto. Lightweight can make Opera run more efficiently in every devices and platforms, even those former non-smart devices using J2ME. This is the reason why people used to love Opera. As Presto stood for itself, there were some unique but useful JavaScript APIs available.

So **why Opera has given up its OWN powerful engine**, and rather to hug Google's Chromium? And why won't Opera publish Presto's source, even though it has already been given up?

P.S.  How great if Opera developed a new cross-platform desktop app framework like Electron, with its own lightweight Presto... In Electron-based apps, the binary with Chromium engine takes plenty of space (for example, 71MB).

**Comment by anasram** [comment]
At least, opening Presto's source keeps it alive.

**Comment by nowaktz** [comment]
Thanks for your nice words!

You can read about rationale behind switching to Presto here:
https://blogs.opera.com/security/2017/01/legacy-opera-presto-source-code-appearance-online-sharing-sites/

**Comment by mcirsta** [comment]
Actually I've found the source code for Presto that was leaked. Once it leaks it's hard to stop it from spreading.
 I took a look and actually got it to compile on my Ubuntu 23.04 using KDE 5. 
  
 I can confirm that:
1. There's a lot of legacy stuff there as expected, lots of things left from way back which is typical in enterprise software.
2. It's not a bit rusty and not up to speed with the latest things on the web.

I personally have found it interesting but it would probably take a lot of work to bring it back or maintain it and I'm not sure it's that the code itself is that good so that this is worth it.

I'm also not sure this code is worth keeping closed source anymore.... It's far from cutting edge today and it's available anyway.

**Comment by Nuihc88** [comment]
It it were to ever get officially / legally released as open source, it could then be openly worked on and updated to newer web standards. If maintained by open source community, the development costs to Opera Software would be non-existent and once competitive again Opera could then choose to start using it again if they so choose. Win-Win-Win?

**Comment by mcirsta** [comment]
> It it were to ever get officially / legally released as open source, it could then be openly worked on and updated to newer web standards. If maintained by open source community, the development costs to Opera Software would be non-existent and once competitive again Opera could then choose to start using it again if they so choose. Win-Win-Win?

Honestly after spending some more time with the leaked Presto code I'm no longer sure it's really worth it. The code itself is OKish but the inter dependencies are just awful. This depends on that and then on that , remove some stuff and it doesn't work anymore.
 Having its own UI, own rendering engine and own OpenSSL ( modifications on top of OpenSSL ) makes things even harder.
 Add to that there's support for Opera Mini, Opera Turbo and some other stuff that's now long deprecate and you have a real mess that maybe is just not worth it.
  I'm not a fan of Chromium and its code base but looking at the Presto stuff that was leaked I can kinda understand the decision to drop it.
   Instead if someone is interested in a new open source rendering engine there's Ladybird and Neosurf.
