### ISSUE TITLE
[question] how do I compile opera to ARMHF devices?

### ISSUE THREAD

**Issue by Lion4K** [operasoftware/devopera#625]
I'm trying to use opera in my raspberry pi 3 board running Raspbian OS.

**Comment by Lion4K** [comment]
Nothing??

**Comment by fsoder** [comment]
The short - and perhaps blunt - answer is that you don't. To do that you would need the source code.

**Comment by Lion4K** [comment]
Makes sense @fsoder .

Thanks.
